# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_projeto
spring.datasource.username=usuario
spring.datasource.password=senha_forte
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
jwt.expiration=86400000