spring.application.name=meu-projeto

spring.profiles.active=postgres,kafka

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=
jwt.expiration=86400000

admin.seed.firstName=Admin
admin.seed.lastName=Course
admin.seed.email=admin@course.com
admin.seed.password=${ADMIN_SEED_PASSWORD:MaluZoe}