# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_projeto
spring.datasource.username=usuario
spring.datasource.password=senha_forte
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=sua-chave-base64-aqui
jwt.expiration=86400000